-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."SoftcardDimDate"
(
    date_id integer NOT NULL,
    date date,
    year integer,
    month smallint,
    month_name character varying(15),
    week smallint,
    day smallint,
    day_of_week smallint,
    day_of_week_name character varying(10),
    PRIMARY KEY (date_id)
);

CREATE TABLE public."softcardDimCategory"
(
    category_id integer NOT NULL,
    category character varying(50),
    PRIMARY KEY (category_id)
);

CREATE TABLE public."softcardDimItem"
(
    item_id integer NOT NULL,
    item character varying(50),
    PRIMARY KEY (item_id)
);

CREATE TABLE public."softcardDimCountry"
(
    country_id integer NOT NULL,
    country character varying(30),
    PRIMARY KEY (country_id)
);

CREATE TABLE public."softcardFactSales"
(
    date_id integer,
    item_id integer,
    category_id integer,
    country_id integer,
    quantity integer,
    price integer,
    order_id integer NOT NULL,
    PRIMARY KEY (order_id)
);

ALTER TABLE public."softcardFactSales"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcardDimItem" (item_id)
    NOT VALID;


ALTER TABLE public."softcardFactSales"
    ADD FOREIGN KEY (date_id)
    REFERENCES public."SoftcardDimDate" (date_id)
    NOT VALID;


ALTER TABLE public."softcardFactSales"
    ADD FOREIGN KEY (category_id)
    REFERENCES public."softcardDimCategory" (category_id)
    NOT VALID;


ALTER TABLE public."softcardFactSales"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."softcardDimCountry" (country_id)
    NOT VALID;

END;
